server:
  port: 8080
  ssl:
    enabled: true  # Habilita SSL
    key-store: classpath:keystore/identity-service.p12
    key-store-password: TuContrasenaSegura123!
    key-store-type: PKCS12
    key-alias: identity-service



spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: IdentityServiceApi
  datasource:
    url: jdbc:postgresql://localhost:5432/api_identity_service
    username: postgres
    password: 12345
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

#AGREGAR ESTA SECCIoN AQUi - Configuracion JWT
app:
  security:
    jwt:
      secret-key: mTZ4QJAwx+LXWkqZkLkQdUgI6cb81+Pi0g1e9coWezzEOjElEMcwbRnRFFknUnztw6thx1HxXgCn3OWsn4OEWg==
      expiration: 3600000   # 1 hora en milisegundos
      issuer: admin-service
      token:
        refresh-expiration: 86400000  # 24 horas en milisegundos

logging:
  level:
    root: INFO
    com.netdatel: DEBUG
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/identity-service.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.netdatel.identityserviceapi
