server:
  port: 8081
  servlet:
    context-path: /api
  ssl:
    enabled: false # momentneo
    key-store: classpath:keystore/identity-service.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: identity-service

spring:
  application:
    name: IdentityServiceApi
  datasource:
    url: jdbc:postgresql://localhost:5432/api_identity_service
    username: postgres
    password: 12345
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

security:
  jwt:
    token:
      secret-key: TmdiB6UxLQhxTBf3zmcS7QnSxwp8WDkk # temporal
      expiration: 3600000  # 1 hora en milisegundos
      refresh-expiration: 86400000  # 24 horas en milisegundos


logging:
  level:
    root: INFO
    com.netdatel: DEBUG
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/identity-service.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.netdatel.identityserviceapi
